<a href="https://colab.research.google.com/github/CamposJoao/Numerical-Methods/blob/main/Sistemas_de_Equacoes_Lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Departamento de Engenharia de Teleinformática
### AP2 Computação Numérica
### Prof. Tarcisio Ferreira Maciel, Dr.-Ing. ([maciel@ufc.br](mailto:maciel@ufc.br))

### Identificação do aluno
**Nome:** João Pedro Silva Campos

**Matrícula:** 405039

In [ ]:
import numpy as np # Biblioteca para manipular vetores e matrizes (arranjos)

### Questão - Substituição Regressiva

Implemente uma função ```back_substitution(...)``` em Python 3.X que implemente o método da **substituição regressiva** e que receba como parâmetros uma matrix triangular superior ```A``` e um vetor ```b``` e que retorne um vetor ```x``` com a solução do sistema linear triangular, se houver. A função deve:
1. Respeitar a especificação de parâmetros indicada acima e conter documentação de todo o código na forma de comentários.
2. Retornar a solução do sistema quando os dados de entrada forem válidos.
3. Verificar o fornecimento de dados inválidos, interrompendo a função, retornando ```None```, e imprimindo uma mensagem de erro adequada.
4. O uso da função deve ser demonstrado com um exemplo de aplicação devidamente documentado.

In [ ]:
# A função aplica o método da substituição regressiva
# A função recebe a matriz triangular superior A e o vetor b
def back_substitution(A, b, disp=False):
  # Número de linhas da matriz A
  L = np.size(A,0)
  # Número de colunas da matriz A
  C = np.size(A,1)
  # Verificação do fornecimento de dados inválidos
  if C != L:
    print("A matriz A não é quadrada")
    if L != np.size(b):
      print("O número de linhas da matriz A é diferente do número de elementos do vetor b")
      return
    return
  for j in range(0,C):
    if A[j][j] == 0:
      print("A matriz A tem elemento nulo na diagonal")
      return
    for i in range(j+1,L):
      if A[i][j] != 0:
        print("A matriz A não é triangular superior")
        return

  # Incorpora o vetor coluna b à matriz A
  ab = np.insert(A, L, b, axis=1)
  # Número de linhas de matriz extendida ab
  L = np.size(ab,0)
  # Número de colunas da matriz extendida ab
  C = np.size(ab,1)
  # Cria um vetor x de zeros para armazenar a solução do sistema linear triangular
  x = np.zeros(L)
  # Substituição regressiva
  x[L-1] = ab[L-1][C-1]/ab[L-1][L-1]
  for i in range(L-2,-1,-1):
    for j in range(i+1,L):
      x[i] = x[i] + ab[i][j]*x[j] 
    x[i] = (ab[i][C-1] - x[i])/ab[i][i]
  # A função retorna o vetor x com a solução do sistema linear triangular
  return x

In [ ]:
# Variáveis de entrada:
# Matriz triangular superior A
A = np.array([[1, 2, -2], [0, -1, 5], [0, 0, -18]], dtype=float)
# Vetor b
b = np.array([9, 5, -36], dtype=float)

# Chama a função de substituição regressiva e passa os valores de A e b
# Escreve o vetor x com a solução do sistema linear triangular
print("O valor do vetor x é: ", back_substitution(A, b, disp=True))

O valor do vetor x é:  [3. 5. 2.]


**Fonte do código:** 

*   Slide 98 do material da disciplina
*   Exemplo de aplicação adaptado da questão 4.1 do livro Métodos Numéricos para Engenheiros e Cientistas - Gilat
*   Substituição regressiva adaptada do Exemplo 4-2: Função criada no MATLAB para resolver um sistema de equações usando a eliminação de Gauss do livro Métodos Numéricos para Engenheiros e Cientistas - Gilat





### Questão - Substituição Progressiva

Implemente uma função ```forward_substitution(...)``` em Python 3.X que implemente o método da **substituição progressiva** e que receba como parâmetros uma matrix triangular inferior ```A``` e um vetor ```b``` e que retorne um vetor ```x``` com a solução do sistema linear triangular, se houver. A função deve:
1. Respeitar a especificação de parâmetros indicada acima e conter documentação de todo o código na forma de comentários.
2. Retornar a solução do sistema quando os dados de entrada forem válidos.
3. Verificar o fornecimento de dados inválidos, interrompendo a função, retornando ```None```, e imprimindo uma mensagem de erro adequada.
4. O uso da função deve ser demonstrado com um exemplo de aplicação devidamente documentado.

In [ ]:
# A função aplica o método da substituição progressiva
# A função recebe a matriz triangular inferior A e o vetor b
def forward_substitution(A, b, disp=False):
  # Número de linhas da matriz A
  L = np.size(A,0)
  # Número de colunas da matriz A
  C = np.size(A,1)
  # Verificação do fornecimento de dados inválidos
  if C != L:
    print("A matriz A não é quadrada")
    if L != np.size(b):
      print("O número de linhas da matriz A é diferente do número de elementos do vetor b")
      return
    return
  for i in range(L-1,-1,-1):
    if A[i][i] == 0:
      print("A matriz A tem elemento nulo na diagonal")
      return
    for j in range(i+1,C):
      if A[i][j] != 0:
        print("A matriz A não é triangular superior")
        return
  # Incorpora o vetor coluna b à matriz A
  ab = np.insert(A, L, b, axis=1)
  # Número de linhas de matriz extendida ab
  L = np.size(ab,0)
  # Número de colunas da matriz extendida ab
  C = np.size(ab,1)
  # Cria um vetor x de zeros para armazenar a solução do sistema linear triangular
  x = np.zeros(L)
  # Substituição progressiva
  x[0] = ab[0][C-1]/ab[0][0]
  for i in range(1,L):
    for j in range(0,i):
      x[i] = x[i] + ab[i][j]*x[j] 
    x[i] = (ab[i][C-1] - x[i])/ab[i][i]
  # A função retorna o vetor x com a solução do sistema linear triangular  
  return x

In [ ]:
# Variáveis de entrada:
# Matriz triangular inferior A
A = np.array([[-6, 0, 0], [7, -1, 0], [-2, 6, -2]], dtype=float)
# Vetor b
b = np.array([-12, 13, -6], dtype=float)

# Chama a função de substituição progressiva e passa os valores de A e b
# Escreve o vetor x com a solução do sistema linear triangular
print("O valor do vetor x é: ", forward_substitution(A, b, disp=True))

O valor do vetor x é:  [2. 1. 4.]


**Fonte do código:**

*   Exemplo de aplicação adaptado da questão 4.2 do livro Métodos Numéricos para Engenheiros e Cientistas - Gilat
*   Substituição progressiva adaptada do livro Métodos Numéricos para Engenheiros e Cientistas - Gilat - página 116



### Questão - Eliminação de Gauss com Pivotação Parcial

Implemente uma função ```gauss_elimination(...)``` em Python 3.X que implemente a **eliminação de Gauss com pivotação parcial** e que receba como parâmetro uma matrix  quadrada ```A```e um vetor ```b``` de dimensões adequadas e que retorne um vetor ```x``` com a solução do sistema linear, se houver. A função deve:
1. Respeitar a especificação de parâmetros indicada acima e conter documentação de todo o código na forma de comentários.
2. Retornar a solução do sistema quando os dados de entrada forem válidos.
3. Verificar o fornecimento de dados inválidos, interrompendo a função, retornando ```None```, e imprimindo uma mensagem de erro adequada.
4. O uso da função deve ser demonstrado com um exemplo de aplicação devidamente documentado.

In [ ]:
# Implementa o Método de eliminação de Gauss (eliminação progressiva)
# A função resolve um sistema de equações lineares [A][x]=[b] 
# usando o método de eliminação de Gauss (eliminação progressiva)
def gauss_elimination(A, b, disp=False):
  # Número de linhas da matriz A
  L = np.size(A,0)
  # Número de colunas da matriz A
  C = np.size(A,1)
  # Verificação do fornecimento de dados inválidos
  if C != L:
    print("A matriz A não é quadrada")
    if L != np.size(b):
      print("O número de linhas da matriz A é diferente do número de elementos do vetor b")
      return
    return
  # Incorpora o vetor coluna [b] à matriz [A]
  ab = np.insert(A, L, b, axis=1)
  if disp:
    print("A matriz que incorpora o vetor coluna [b] à matriz [A] é:")
    print(ab)
  # Número de linhas de matriz extendida ab
  L = np.size(ab,0)
  # Número de colunas de matriz extendida ab
  C = np.size(ab,1)

  # Procedimento de pivotação parcial
  for j in range(0,L):
    for i in range(j+1,C-1):
      if abs(ab[j][j]) < abs(ab[i][j]):
        ab[[j,i]] = ab[[i,j]]
  if disp:
    print("A matriz após o procedimento de pivotação é:")
    print(ab)

  # Procedimento de eliminação de Gauss (eliminação progressiva)
  for j in range(0,L-1):
    for i in range(j+1,L):
      for k in range(j-L,C-1):
        ab[i][k] = ab[i][k] - ab[i][j]/ab[j][j]*ab[j][k]
  if disp:
    print("A matriz resultado da eliminação de Gauss (eliminação progressiva) é:")
    print(ab)
  # Cria um vetor x de zeros para armazenar a solução do sistema linear triangular
  x = np.zeros(L)

  # Substituição regressiva
  x[L-1] = ab[L-1][C-1]/ab[L-1][L-1]
  for i in range(L-2,-1,-1):
    for j in range(i+1,L):
      x[i] = x[i] + ab[i][j]*x[j] 
    x[i] = (ab[i][C-1] - x[i])/ab[i][i]
  return x

In [ ]:
# Variáveis de entrada:
# Matriz A de coeficientes
A = np.array([[0, 2, 3], [4, -3, 2], [2, 4, -3]], dtype=float)
# Vetor b coluna contendo as constantes do lado direito do sistema
b = np.array([46, 16, 12], dtype=float)

# Aplica o Método de eliminação de Gauss (eliminação progressiva)
print("Método de eliminação de Gauss (eliminação progressiva)")
print("======================================================")
print("O valor de x é", gauss_elimination(A, b, disp=True))

Método de eliminação de Gauss (eliminação progressiva)
A matriz que incorpora o vetor coluna [b] à matriz [A] é:
[[ 0.  2.  3. 46.]
 [ 4. -3.  2. 16.]
 [ 2.  4. -3. 12.]]
3 linhas e 4 colunas na matriz
A matriz após o procedimento de pivotação é:
[[ 4. -3.  2. 16.]
 [ 2.  4. -3. 12.]
 [ 0.  2.  3. 46.]]
A matriz resultado da eliminação de Gauss (eliminação progressiva) é:
[[ 4.         -3.          2.         16.        ]
 [ 0.          5.5        -4.          4.        ]
 [ 0.          0.          4.45454545 44.54545455]]
O valor de x é [ 5.  8. 10.]


**Fonte do código:**

*   Método da eliminação de Gauss (eliminação progressiva) adaptado do Exemplo 4-2: Função criada no MATLAB para resolver um sistema de equações usando a eliminação de Gauss do livro Métodos Numéricos para Engenheiros e Cientistas - Gilat
*   Método de pivotação parcial adaptado da explicação da página 216 e 217 do livro Métodos Numéricos para Engenharia - Chapra
*   Exemplo de aplicação adaptado da explicação do algoritmo de eliminação de Gauss e a pivotação no slide 110 e 111 da disciplina





### Questão - Gauss-Seidel

In [ ]:
a = np.array([[9, -2, 3, 2], [2, 8, -2, 3], [-3, 2, 11, -4], [-2, 3, 2, 10]], dtype=float)
b = np.array([54.5, -14, 12.5, -21], dtype=float)
# Número de linhas
L = np.size(a,0)
# Número de colunas
C = np.size(a,1)
# Valores iniciais para i = 1
x = np.zeros(L)
# Número de interações
interacoes = 9

for k in range(1,interacoes):
  print(x,k)
  for i in range(0,L):
    somatorio = 0.0
    for j in range(0,C):
      if j != i:
        somatorio = somatorio + (a[i][j]*x[j])
      x[i] = (b[i] - somatorio)/a[i][i]

[0. 0. 0. 0.] 1
[ 6.05555556 -3.26388889  3.38131313 -0.58598485] 2
[ 4.33336139 -1.76826775  2.4266073  -1.18816886] 3
[ 5.11777559 -1.97722875  2.45955535 -0.97518733] 4
[ 5.0130279  -2.02267289  2.5166982  -0.99393219] 5
[ 4.98804711 -1.99511266  2.49805799 -1.00346838] 6
[ 5.00250416 -1.9998109   2.49938734 -0.99943337] 7
[ 5.00012032 -2.00039573  2.50031082 -0.99991938] 8


**Fonte do código:**


*   Exemplo 4.8: Solução de um conjunto de quatro equações lineares usando o método de Gauss-Seidel

*   Página 148 do livro Métodos Numéricos para Engenheiros e Cientistas




### Questão - Jacobi

In [ ]:
a = 3.0
b = 4.0
c = 5.0
A = np.array([[a, b/20, c/20], [a/20, -b, c/20], [-a/20, -b/20, c]], dtype=float)
be = np.array([a*b, a*c, b*c], dtype=float)
# Número de linhas
L = np.size(A,0)
# Número de colunas
C = np.size(A,1)
# Valores iniciais para i = 1
x = np.zeros(L)
# Número de interações
interacoes = 3
print(A)
print(be)
print(x)
xnew = np.zeros(L)
for k in range(1,interacoes):
  for i in range(0,L):
    somatorio = 0.0
    for j in range(0,C):
      if j != i:
        somatorio = somatorio + (A[i][j]*x[j])
      xnew[i] = (be[i] - somatorio)/A[i][i]
  x = xnew.copy()
  print(xnew)

[[ 3.    0.2   0.25]
 [ 0.15 -4.    0.25]
 [-0.15 -0.2   5.  ]]
[12. 15. 20.]
[0. 0. 0.]
[ 4.   -3.75  4.  ]
[ 3.91666667 -3.35        3.97      ]
